### ISSUE TITLE
hsl function is not supported in Medical Director Sidebar Widget

### ISSUE THREAD

**Issue by Susros** [MedicalDirector/hxui-css#17]

**Comment by matcur-md** [comment]
@Susros do you mind providing some information about your environment?
- sass version
- build tool
- etc

**Comment by Susros** [comment]
@matcur-md I am using sass version `1.52.1`, hxui/css version `1.5.5` for react app. I currently resolved the issue by overriding colour hsl function with hex code on my own `_variables.scss`.  I think MD sidebar is using IE, which doesn't support hsl colour function.
